version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Berlin"
    groups:
      all-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
      all-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
