import { StyleSheet } from "react-native";
import type { AppTheme } from "./theme";

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    backgroundLayer: {
      ...StyleSheet.absoluteFillObject,
      overflow: "hidden",
    },
    backgroundOrbOne: {
      position: "absolute",
      top: -140,
      left: -120,
      width: 280,
      height: 280,
      borderRadius: 140,
      backgroundColor: theme.primaryGlow,
    },
    backgroundOrbTwo: {
      position: "absolute",
      top: -90,
      right: -140,
      width: 300,
      height: 300,
      borderRadius: 150,
      backgroundColor:
        theme.direction === "gazette"
          ? "rgba(232, 184, 75, 0.14)"
          : "rgba(17, 19, 24, 0.12)",
    },
    listContent: {
      paddingBottom: 44,
    },
    center: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 20,
    },
    loadingText: {
      marginTop: 12,
      color: theme.textMuted,
    },
    header: {
      paddingHorizontal: 12,
      paddingTop: 12,
      gap: 16,
    },
    directionSwitch: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      paddingHorizontal: 20,
      alignItems: "center",
    },
    directionButton: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceMuted,
      paddingHorizontal: 12,
      paddingVertical: 7,
    },
    directionButtonActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primarySoft,
    },
    directionButtonText: {
      color: theme.textSoft,
      fontSize: 11,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    directionButtonTextActive: {
      color: theme.primary,
    },
    heroPanel: {
      borderRadius: 28,
      overflow: "hidden",
      borderWidth: 1,
      borderColor:
        theme.direction === "gazette"
          ? "rgba(232, 184, 75, 0.35)"
          : "rgba(255, 255, 255, 0.2)",
      backgroundColor: theme.heroBase,
      shadowColor: theme.direction === "gazette" ? "#120e0a" : "rgba(14, 16, 21, 0.9)",
      shadowOpacity: 0.32,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 12 },
      elevation: 8,
    },
    heroPulseOne: {
      position: "absolute",
      top: -100,
      left: -60,
      width: 260,
      height: 260,
      borderRadius: 130,
      backgroundColor:
        theme.direction === "gazette"
          ? "rgba(255, 236, 212, 0.2)"
          : "rgba(255, 255, 255, 0.18)",
    },
    heroPulseTwo: {
      position: "absolute",
      top: -120,
      right: -80,
      width: 260,
      height: 260,
      borderRadius: 130,
      backgroundColor: theme.primaryGlow,
    },
    heroGrid: {
      paddingHorizontal: 18,
      paddingVertical: 18,
      gap: 10,
      backgroundColor: "transparent",
    },
    heroTagRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    heroTag: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.heroTagBorder,
      backgroundColor: theme.heroTagBg,
      paddingHorizontal: 12,
      paddingVertical: 5,
    },
    heroTagText: {
      color: theme.heroText,
      fontSize: 11,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    heroKicker: {
      color: theme.heroTextMuted,
      fontSize: 13,
      fontWeight: "600",
    },
    heroTitle: {
      color: theme.heroText,
      fontSize: 36,
      lineHeight: 34,
      fontWeight: "800",
      textTransform: theme.direction === "gazette" ? "none" : "uppercase",
      letterSpacing: theme.direction === "gazette" ? 0.3 : 1.2,
    },
    heroTitleAccent: {
      color: theme.primary,
    },
    heroDescription: {
      color: theme.heroTextMuted,
      fontSize: 14,
      lineHeight: 20,
      maxWidth: 460,
    },
    section: {
      paddingHorizontal: 20,
      paddingTop: 2,
      marginTop: 12,
      gap: 4,
    },
    sectionKicker: {
      color: theme.primary,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 1.6,
    },
    sectionTitle: {
      color: theme.text,
      fontSize: 29,
      lineHeight: 30,
      fontWeight: "800",
      textTransform: theme.direction === "gazette" ? "none" : "uppercase",
      letterSpacing: theme.direction === "gazette" ? 0.3 : 1.2,
    },
    sectionSubtitle: {
      color: theme.textMuted,
      marginBottom: 8,
      fontSize: 13,
    },
    tabs: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      paddingHorizontal: 20,
      marginTop: -3,
    },
    tab: {
      paddingVertical: 9,
      paddingHorizontal: 14,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceMuted,
    },
    tabActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primarySoft,
      shadowColor: theme.primary,
      shadowOpacity: 0.18,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 3,
    },
    tabText: {
      color: theme.textSoft,
      fontSize: 12,
      fontWeight: "700",
    },
    tabTextActive: {
      color: theme.primary,
    },
    featuredCard: {
      marginHorizontal: 20,
      borderRadius: 24,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      shadowColor: theme.direction === "gazette" ? "#1a1612" : "#0a0c12",
      shadowOpacity: 0.12,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 10 },
      elevation: 5,
    },
    featuredBanner: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: theme.heroHighlight,
      borderBottomWidth: 1,
      borderBottomColor:
        theme.direction === "gazette"
          ? "rgba(232, 184, 75, 0.35)"
          : "rgba(255, 255, 255, 0.22)",
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      alignItems: "center",
      justifyContent: "space-between",
    },
    featuredBadge: {
      borderRadius: 999,
      paddingHorizontal: 11,
      paddingVertical: 5,
      borderWidth: 1,
      borderColor:
        theme.direction === "gazette"
          ? "rgba(232, 184, 75, 0.45)"
          : "rgba(255, 255, 255, 0.36)",
      backgroundColor:
        theme.direction === "gazette"
          ? "rgba(255, 255, 255, 0.08)"
          : "rgba(255, 255, 255, 0.12)",
    },
    featuredBadgeText: {
      color: theme.heroText,
      fontSize: 10,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    featuredBody: {
      paddingHorizontal: 16,
      paddingVertical: 16,
      gap: 10,
    },
    featuredTitle: {
      color: theme.text,
      fontSize: 28,
      lineHeight: 30,
      fontWeight: "800",
      textTransform: theme.direction === "gazette" ? "none" : "uppercase",
      letterSpacing: theme.direction === "gazette" ? 0.4 : 1,
    },
    featuredSummary: {
      color: theme.textMuted,
      fontSize: 14,
      lineHeight: 20,
    },
    featuredMetaRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    featuredMetaChip: {
      borderRadius: 999,
      backgroundColor: theme.surfaceMuted,
      paddingHorizontal: 11,
      paddingVertical: 6,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
    },
    featuredMetaText: {
      color: theme.textSoft,
      fontSize: 11,
      fontWeight: "700",
    },
    quickActions: {
      marginHorizontal: 20,
      gap: 10,
    },
    quickActionCard: {
      minHeight: 110,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      paddingHorizontal: 14,
      paddingVertical: 14,
      gap: 6,
      shadowColor: theme.direction === "gazette" ? "#1a1612" : "#111319",
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    quickActionLabel: {
      color: theme.primary,
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 1.2,
      textTransform: "uppercase",
    },
    quickActionTitle: {
      color: theme.text,
      fontSize: 21,
      lineHeight: 22,
      fontWeight: "800",
      textTransform: theme.direction === "gazette" ? "none" : "uppercase",
      letterSpacing: theme.direction === "gazette" ? 0.2 : 0.8,
    },
    quickActionDescription: {
      color: theme.textMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    card: {
      marginHorizontal: 20,
      marginVertical: 6,
      padding: 16,
      borderRadius: 20,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: theme.direction === "gazette" ? "#1a1612" : "#0f1015",
      shadowOpacity: 0.08,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 8 },
      elevation: 2,
    },
    cardMetaRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 10,
      gap: 8,
      flexWrap: "wrap",
    },
    cardMetaChip: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.surfaceMuted,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    cardMetaText: {
      color: theme.textSoft,
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    cardMetaStatusFinal: {
      backgroundColor: theme.primarySoft,
      borderColor: theme.primary,
    },
    cardMetaStatusScheduled: {
      backgroundColor: theme.surfaceSoft,
    },
    cardMetaStatusFinalText: {
      color: theme.primary,
    },
    cardMetaStatusScheduledText: {
      color: theme.textSoft,
    },
    teamRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flex: 1,
      minWidth: 0,
      justifyContent: "space-between",
    },
    teamLabelRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      flex: 1,
      minWidth: 0,
    },
    teamLabelRowSecondary: {
      marginTop: 10,
    },
    team: {
      color: theme.text,
      fontSize: 16,
      fontWeight: "700",
    },
    score: {
      color: theme.primary,
      fontSize: 22,
      fontWeight: "800",
      letterSpacing: theme.direction === "gazette" ? 0.1 : 0.8,
    },
    teamLogoFrame: {
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.logoBg,
      borderWidth: 1,
      borderColor: theme.logoBorder,
      overflow: "hidden",
    },
    teamLogoFallback: {
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.logoBg,
      borderWidth: 1,
      borderColor: theme.logoBorder,
    },
    teamLogoFallbackText: {
      color: theme.text,
      fontWeight: "700",
    },
    goalList: {
      marginTop: 12,
      gap: 4,
    },
    goalItem: {
      color: theme.textSoft,
      fontSize: 12,
    },
    emptyState: {
      marginTop: 6,
      padding: 14,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.emptyBg,
    },
    emptyText: {
      color: theme.textMuted,
      textAlign: "center",
    },
    errorBanner: {
      marginHorizontal: 20,
      marginTop: 4,
      padding: 13,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.warningBorder,
      backgroundColor: theme.warningBg,
    },
    errorText: {
      color: theme.warningText,
      fontSize: 13,
    },
    tableRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 12,
      paddingHorizontal: 14,
      marginHorizontal: 20,
      marginVertical: 4,
      borderRadius: 16,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      gap: 10,
    },
    tableRowLeader: {
      backgroundColor: theme.direction === "gazette" ? "#fcf4e5" : "#15261f",
      borderColor: theme.direction === "gazette" ? "#dcc8a0" : "#2d553f",
    },
    tableRowEurope: {
      backgroundColor: theme.direction === "gazette" ? "#fffcf6" : "#151a22",
      borderColor: theme.direction === "gazette" ? "#e6dac5" : "#2a3441",
    },
    tableRowBottom: {
      backgroundColor: theme.direction === "gazette" ? "#f8f2ea" : "#23171d",
      borderColor: theme.direction === "gazette" ? "#e1d7ca" : "#46303a",
    },
    tablePosBadge: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.direction === "gazette" ? "#f2ebe1" : "#1d2431",
      marginRight: 6,
    },
    tablePosLeader: {
      backgroundColor: theme.primary,
    },
    tablePosEurope: {
      backgroundColor: theme.direction === "gazette" ? "#efe6d6" : "#1f2835",
    },
    tablePosBottom: {
      backgroundColor: theme.direction === "gazette" ? "#ece2d5" : "#3a2530",
    },
    tablePosText: {
      color: theme.direction === "gazette" ? "#60594e" : "#98a4bb",
      fontSize: 12,
      fontWeight: "800",
    },
    tablePosTextLeader: {
      color: "#ffffff",
    },
    tablePosTextEurope: {
      color: theme.direction === "gazette" ? "#8c6c2c" : "#8aa0c0",
    },
    tablePosTextBottom: {
      color: theme.direction === "gazette" ? "#5f5547" : "#f2bdcb",
    },
    tableMain: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
      gap: 8,
      minWidth: 0,
    },
    tableCellTeam: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
      gap: 7,
      minWidth: 0,
    },
    tableCellTeamText: {
      flexShrink: 1,
      color: theme.text,
      fontSize: 14,
      fontWeight: "700",
    },
    tableMeta: {
      alignItems: "flex-end",
      gap: 2,
    },
    tableZone: {
      color: theme.textSoft,
      fontSize: 10,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    tableCellPts: {
      color: theme.primary,
      fontSize: 16,
      fontWeight: "800",
    },
    tableStatsRow: {
      marginHorizontal: 20,
      marginBottom: 8,
      paddingHorizontal: 14,
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 10,
    },
    tableStat: {
      color: theme.textSoft,
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    bracketCard: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      paddingVertical: 10,
      shadowColor: theme.direction === "gazette" ? "#1a1612" : "#10131b",
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    roundTitle: {
      color: theme.textSoft,
      textTransform: "uppercase",
      letterSpacing: 1.2,
      fontSize: 11,
      fontWeight: "800",
      marginBottom: 8,
      marginTop: 8,
    },
  });

export type AppStyles = ReturnType<typeof createStyles>;
