import type { AppTheme } from "../types";

export const createHomeStyles = (theme: AppTheme) => ({
  header: {
    paddingHorizontal: 12,
    paddingTop: 12,
    gap: 16,
  },
  heroPanel: {
    borderRadius: 28,
    overflow: "hidden" as const,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    backgroundColor: theme.heroBase,
    shadowColor: "rgba(14, 16, 21, 0.9)",
    shadowOpacity: 0.32,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  heroPulseOne: {
    position: "absolute" as const,
    top: -100,
    left: -60,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: "rgba(255, 255, 255, 0.18)",
  },
  heroPulseTwo: {
    position: "absolute" as const,
    top: -120,
    right: -80,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: theme.primaryGlow,
  },
  heroGrid: {
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 10,
    backgroundColor: "transparent",
  },
  heroTagRow: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 8,
  },
  heroTag: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.heroTagBorder,
    backgroundColor: theme.heroTagBg,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  heroTagText: {
    color: theme.heroText,
    fontSize: 11,
    fontWeight: "700" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 0.8,
  },
  heroKicker: {
    color: theme.heroTextMuted,
    fontSize: 13,
    fontWeight: "600" as const,
  },
  heroTitle: {
    color: theme.heroText,
    fontSize: 36,
    lineHeight: 34,
    fontWeight: "800" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 1.2,
  },
  heroTitleAccent: {
    color: theme.primary,
  },
  heroDescription: {
    color: theme.heroTextMuted,
    fontSize: 14,
    lineHeight: 20,
    maxWidth: 460,
  },
  section: {
    paddingHorizontal: 20,
    paddingTop: 2,
    marginTop: 12,
    gap: 4,
  },
  sectionKicker: {
    color: theme.primary,
    fontSize: 11,
    fontWeight: "800" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 1.6,
  },
  sectionTitle: {
    color: theme.text,
    fontSize: 29,
    lineHeight: 30,
    fontWeight: "800" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 1.2,
  },
  sectionSubtitle: {
    color: theme.textMuted,
    marginBottom: 8,
    fontSize: 13,
  },
  tabs: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 10,
    paddingHorizontal: 20,
    marginTop: -3,
  },
  tab: {
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.surfaceMuted,
  },
  tabActive: {
    borderColor: theme.primary,
    backgroundColor: theme.primarySoft,
    shadowColor: theme.primary,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  tabText: {
    color: theme.textSoft,
    fontSize: 12,
    fontWeight: "700" as const,
  },
  tabTextActive: {
    color: theme.primary,
  },
  quickActions: {
    marginHorizontal: 20,
    gap: 10,
  },
  quickActionCard: {
    minHeight: 110,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.surface,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 6,
    shadowColor: "#111319",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  quickActionLabel: {
    color: theme.primary,
    fontSize: 11,
    fontWeight: "800" as const,
    letterSpacing: 1.2,
    textTransform: "uppercase" as const,
  },
  quickActionTitle: {
    color: theme.text,
    fontSize: 21,
    lineHeight: 22,
    fontWeight: "800" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 0.8,
  },
  quickActionDescription: {
    color: theme.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  emptyState: {
    marginTop: 6,
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.emptyBg,
  },
  emptyText: {
    color: theme.textMuted,
    textAlign: "center" as const,
  },
  errorBanner: {
    marginHorizontal: 20,
    marginTop: 4,
    padding: 13,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.warningBorder,
    backgroundColor: theme.warningBg,
  },
  errorText: {
    color: theme.warningText,
    fontSize: 13,
  },
});
