import type { AppTheme } from "../types";

export const createHomeStyles = (theme: AppTheme) => ({
  header: {
    paddingHorizontal: 12,
    paddingTop: 12,
    gap: 16,
  },
  heroCard: {
    marginHorizontal: 12,
    marginTop: 4,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: "#10201d",
    overflow: "hidden" as const,
    shadowColor: "#05070b",
    shadowOpacity: 0.28,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 7,
  },
  heroGlow: {
    position: "absolute" as const,
    top: -20,
    right: -10,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: "rgba(213, 0, 29, 0.22)",
  },
  heroGrid: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    gap: 12,
  },
  heroCopy: {
    gap: 10,
    paddingRight: 8,
  },
  heroKicker: {
    color: "#ffd86b",
    fontSize: 11,
    fontWeight: "800" as const,
    letterSpacing: 1.8,
    textTransform: "uppercase" as const,
  },
  heroTitle: {
    color: theme.text,
    fontSize: 34,
    lineHeight: 34,
    fontWeight: "800" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 1.1,
  },
  heroDescription: {
    color: theme.textMuted,
    fontSize: 13,
    lineHeight: 19,
    maxWidth: 240,
  },
  heroBadges: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 8,
  },
  heroBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(8, 13, 17, 0.28)",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  heroBadgeText: {
    color: theme.text,
    fontSize: 11,
    fontWeight: "700" as const,
  },
  heroMascotWrap: {
    alignSelf: "flex-end" as const,
    width: 150,
    height: 220,
    justifyContent: "flex-end" as const,
    alignItems: "center" as const,
  },
  heroMascotShadow: {
    position: "absolute" as const,
    bottom: 8,
    width: 86,
    height: 16,
    borderRadius: 999,
    backgroundColor: "rgba(4, 6, 8, 0.68)",
  },
  heroMascot: {
    width: 150,
    height: 220,
  },
  section: {
    paddingHorizontal: 20,
    paddingTop: 2,
    marginTop: 12,
    gap: 4,
  },
  sectionKicker: {
    color: theme.primary,
    fontSize: 11,
    fontWeight: "800" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 1.6,
  },
  sectionTitle: {
    color: theme.text,
    fontSize: 29,
    lineHeight: 30,
    fontWeight: "800" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 1.2,
  },
  sectionSubtitle: {
    color: theme.textMuted,
    marginBottom: 8,
    fontSize: 13,
  },
  tabs: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 10,
    paddingHorizontal: 20,
    marginTop: -3,
  },
  tab: {
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.surfaceMuted,
  },
  tabActive: {
    borderColor: theme.primary,
    backgroundColor: theme.primarySoft,
    shadowColor: theme.primary,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  tabText: {
    color: theme.textSoft,
    fontSize: 12,
    fontWeight: "700" as const,
  },
  tabTextActive: {
    color: theme.primary,
  },
  quickActions: {
    marginHorizontal: 20,
    gap: 10,
  },
  quickActionCard: {
    minHeight: 110,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.surface,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 6,
    shadowColor: "#111319",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  quickActionCardPressed: {
    borderColor: theme.primary,
    backgroundColor: theme.surfaceMuted,
  },
  quickActionCardDisabled: {
    opacity: 0.7,
  },
  quickActionLabel: {
    color: theme.primary,
    fontSize: 11,
    fontWeight: "800" as const,
    letterSpacing: 1.2,
    textTransform: "uppercase" as const,
  },
  quickActionTitle: {
    color: theme.text,
    fontSize: 21,
    lineHeight: 22,
    fontWeight: "800" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 0.8,
  },
  quickActionDescription: {
    color: theme.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  emptyState: {
    marginTop: 6,
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.emptyBg,
  },
  emptyText: {
    color: theme.textMuted,
    textAlign: "center" as const,
  },
  errorBanner: {
    marginHorizontal: 20,
    marginTop: 4,
    padding: 13,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.warningBorder,
    backgroundColor: theme.warningBg,
  },
  errorText: {
    color: theme.warningText,
    fontSize: 13,
  },
});
