import type { AppTheme } from "../types";

export const createMatchdayStyles = (theme: AppTheme) => ({
  card: {
    marginHorizontal: 20,
    marginVertical: 6,
    padding: 16,
    borderRadius: 24,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
    overflow: "hidden" as const,
    shadowColor: "#07030d",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  cardAccentLine: {
    position: "absolute" as const,
    top: 0,
    left: 28,
    right: 28,
    height: 1,
    backgroundColor: "rgba(255, 214, 108, 0.8)",
  },
  cardMetaRow: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    marginBottom: 10,
    gap: 8,
    flexWrap: "wrap" as const,
  },
  cardMetaChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: "rgba(0, 0, 0, 0.18)",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  cardMetaText: {
    color: theme.textSoft,
    fontSize: 11,
    fontFamily: theme.fonts.bodySemibold,
    letterSpacing: 0.2,
  },
  cardMetaStatusFinal: {
    backgroundColor: "rgba(79, 48, 24, 0.6)",
    borderColor: "rgba(255, 214, 108, 0.4)",
  },
  cardMetaStatusScheduled: {
    backgroundColor: "rgba(16, 40, 56, 0.6)",
    borderColor: "rgba(87, 235, 255, 0.3)",
  },
  cardMetaStatusFinalText: {
    color: theme.cream,
  },
  cardMetaStatusScheduledText: {
    color: "#bcf7ff",
  },
  teamRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 10,
    flex: 1,
    minWidth: 0,
    justifyContent: "space-between" as const,
  },
  teamLabelRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  teamLabelRowSecondary: {
    marginTop: 10,
  },
  team: {
    color: theme.text,
    fontSize: 16,
    fontFamily: theme.fonts.bodyBold,
  },
  scorePill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255, 232, 244, 0.16)",
    paddingHorizontal: 14,
    paddingVertical: 9,
    minWidth: 92,
    alignItems: "center" as const,
  },
  score: {
    color: theme.cream,
    fontSize: 25,
    fontFamily: theme.fonts.heading,
    letterSpacing: 0.2,
  },
  goalList: {
    marginTop: 12,
    gap: 4,
  },
  goalItem: {
    color: theme.textMuted,
    fontSize: 12,
    fontFamily: theme.fonts.bodyMedium,
  },
});
