export type AppTheme = {
  background: string;
  backgroundEnd: string;
  surface: string;
  surfaceMuted: string;
  surfaceSoft: string;
  text: string;
  textMuted: string;
  textSoft: string;
  border: string;
  borderSubtle: string;
  primary: string;
  primarySoft: string;
  primaryGlow: string;
  accent: string;
  accentSoft: string;
  accentWarm: string;
  cream: string;
  danger: string;
  warningText: string;
  warningBorder: string;
  warningBg: string;
  emptyBg: string;
  logoBg: string;
  logoBorder: string;
  fonts: {
    heading: string;
    body: string;
    bodyMedium: string;
    bodySemibold: string;
    bodyBold: string;
  };
};
